### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by Softkandi** [Waterdish/zelda3-android#4]
There are no instructions on how to build Zelda3 for Android. For example:

Is Android Studio required or is it enough with the command line tools?
What version?
What version of the NDK should be used?

**Comment by Waterdish** [comment]
It's an android studio project. I don't think a specific version of the ndk is required, but I used the latest one. I don't think a specific sdk version is required, I would just use the one for your device version. The version of android studio I used also was just the latest (2023). Just make sure you use at least sdk 23 if compiling the android 13 branch since that sdk allows you to ask for permissions.

**Comment by Softkandi** [comment]
Thanks. That worked.
I have been able to build it (main branch) and it works fine in my Android 13 phone.
I didn't need the android13 branch. Is that as expected?

**Comment by Waterdish** [comment]
When I made the app it was expected to work on android 13 since apps shouldn't need special permission to access their own data folder, but multiple people mentioned that it wasn't working on android 13 for them and when I made a version of the app that asks for full file permissions, it worked for them. That's good to know though that it works for you.
